Solution
MargoVI/Spring_security pull request #1
Opened 2024-02-09 18:41 UTC by IIMargo

2024-02-10 15:58 UTC, IIMargo commented
доделала, модернизировала

2024-02-10 19:47 UTC, pdasilem requested changes

2024-02-10 19:47 UTC, pdasilem commented on src/main/java/ru/itmentor/spring/boot_security/demo/entity/User.java
> +    @ManyToMany(fetch = FetchType.EAGER)
избавиться от игер

2024-02-11 17:19 UTC, IIMargo commented
интелидж автоматом названия сменила на классы, сейчас заметила, изменила

2024-02-11 17:47 UTC, pdasilem approved these changes

2024-02-11 17:49 UTC, merged